#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-k"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "1201b28d523b4749a8096ac765d720be" }
]

[assets]
directory = "./public"
